services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - D:\docker\volume\sonarqube\data:/opt/sonarqube/data
      - D:\docker\volume\sonarqube\extensions:/opt/sonarqube/extensions
      - D:\docker\volume\sonarqube\logs:/opt/sonarqube/logs
    networks:
      - jenkins_network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: sonar_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - D:\docker\volume\postgres\data:/var/lib/postgresql/data
    networks:
      - jenkins_network

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - D:\docker\volume\jenkins\home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    networks:
      - jenkins_network
    
  grafana:
    image: grafana/grafana:11.2.0
    ports:
      - "3000:3000"
    container_name: grafana
    restart: unless-stopped
    networks:
      - jenkins_network
    volumes:
      - D:\docker\volume\grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini

  prometheus:
    image: prom/prometheus:v2.48.0
    ports:
      - "9090:9090"
    networks:
      - jenkins_network
    volumes:
      - D:\docker\volume\prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  exporter:
    image: prom/node-exporter:latest
    container_name: exporter
    ports:
      - "9100:9100"
    networks:
      - jenkins_network
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"

networks:
  jenkins_network:
    driver: bridge


