global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: node
    static_configs:
      - targets: ['exporter:9100']

  - job_name: 'company-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['comapny:8081']  

  - job_name: 'job-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['job:8082']  

  - job_name: 'review-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['review:8083']  

