Parameters:
  PublicSubnetId:
    Type: String
  JenkinsK3sSecurityGroup:
    Type: String
  GrafanaPrometheusSecurityGroup:
    Type: String
  INSTANCETYPE:
    Type: String
    Default: "t3.medium"
  AMI:
    Type: AWS::EC2::Image::Id
    Default: "ami-0866a3c8686eaeeba"
  Environment:
    Type: String
    Default: "nhom14-project"

Resources:
  JenkinsK3sEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref INSTANCETYPE
      ImageId: !Ref AMI
      SubnetId: !Ref PublicSubnetId
      SecurityGroupIds:
        - !Ref JenkinsK3sSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 25  
            VolumeType: gp2  
            DeleteOnTermination: false  
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-jenkins-k3s"

  PrometheusGrafanaEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref INSTANCETYPE
      ImageId: !Ref AMI
      SubnetId: !Ref PublicSubnetId
      SecurityGroupIds:
        - !Ref GrafanaPrometheusSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 15  
            VolumeType: gp2  
            DeleteOnTermination: false  
      Tags:
        - Key: Name
          Value: !Sub "${Environment}-grafana-prometheus"
 
Outputs:
  JenkinsK3sEC2Id:
    Value: !Ref JenkinsK3sEC2
  PrometheusGrafanaEC2Id:
    Value: !Ref PrometheusGrafanaEC2
