apiVersion: apps/v1
kind: Deployment
metadata:
  name: job
  labels:
    app: job
spec:
  replicas: 1
  template:
    metadata:
      name: job
      labels:
        app: job
    spec:
      containers:
        - name: job
          image: lambaoduy1310/jobms:v3.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      restartPolicy: Always
  selector:
    matchLabels:
      app: job

---

apiVersion: v1
kind: Service
metadata:
  name: job
spec:
  selector:
    app: job
  ports:
    - port: 80
      targetPort: 8082
  type: LoadBalancer
