services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - D:\docker\volume\sonarqube\data:/opt/sonarqube/data
      - D:\docker\volume\sonarqube\extensions:/opt/sonarqube/extensions
      - D:\docker\volume\sonarqube\logs:/opt/sonarqube/logs
    networks:
      - jenkins_network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: sonar_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - D:\docker\volume\postgres\data:/var/lib/postgresql/data
    networks:
      - jenkins_network

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - D:\docker\volume\jenkins\home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    networks:
      - jenkins_network

networks:
  jenkins_network:
    driver: bridge


