pipeline {
    agent any

    tools {
        jdk 'jdk17'
        nodejs 'node18'
        maven 'maven-3.9.9'
        dockerTool 'docker'
    }

    environment {
        SCANNER_HOME        = tool 'sonar-scanner'
        SONAR_KEY_JOB       = 'Job-MS'
        DOCKER_REGISTRY     = 'lambaoduy1310'
        IMAGE_TAG           = "v4.${BUILD_NUMBER}"  
    }

    stages {
        stage('Clean workspace'){
            steps{
                cleanWs()
            }
        }

        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('TRIVY FS SCAN') {
            steps {
                dir('jobms') {
                    echo 'Scanning Files System...'
                    sh "trivy fs ."
                }
            }
        }

        stage('SonarQube Analys for Job MS') {
            steps {
                dir('jobms'){
                    script {
                        withSonarQubeEnv('sonar-server') {
                            sh '${SCANNER_HOME}/bin/sonar-scanner --version'
                            sh """
                                ${SCANNER_HOME}/bin/sonar-scanner \
                                    -Dsonar.java.binaries=target/classes \
                            """
                        }
                    }
                }
            }
        }

        stage('Build Job MS') {
            steps {
                dir('jobms') {
                    timeout(time: 10, unit: 'MINUTES') {
                        script {
                            sh './mvnw -N io.takari:maven:wrapper || true'
                            sh 'chmod +x ./mvnw'
                            
                            sh './mvnw spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=${DOCKER_REGISTRY}/jobms:${IMAGE_TAG}'
                        }
                    }
                }
            }
        }

        stage('Push MS to Docker') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker', toolName: 'docker') {
                        echo 'Pushing to Docker Hub...'
                        sh "docker push ${DOCKER_REGISTRY}/jobms:${IMAGE_TAG}"
                    }
                }
            }
        }

        stage('TRIVY DOCKER IMAGE SCAN') {
            steps {
                echo 'Scanning docker image...'
                sh "trivy image ${DOCKER_REGISTRY}/jobms:${IMAGE_TAG}"
            }
        }
    }

    post {
        always {
            echo 'Cleaning up local Docker images...'
            sh "docker rmi ${DOCKER_REGISTRY}/jobms:${IMAGE_TAG} || true"
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
